name: Lint CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  psf-black:
    name: Format with psf-black
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Black and ISort
        run: pip install black==22.3.0 isort==5.12.0
      - name: Sort Imports
        run: git ls-files -z | grep -Ez -v '(pb2|pb2_grpc)\.py$' | grep -z '\.py$' | xargs -0 python3 -m isort --quiet
      - name: Format Python Code
        run: git ls-files -z | grep -Ez -v '(pb2|pb2_grpc)\.py$' | grep -z '\.py$' | xargs -0 python3 -m black --quiet
      - name: Check Differences After Formatting
        run: git diff --ignore-submodules=all --color --exit-code .
